name: Attacker Controlled Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      injection_point:
        description: 'A scary input to pass to the workflow'
        required: true
        default: 'boo!'
        type: string


jobs:
  flag-success:
    runs-on: ubuntu-24.04

    steps:
      - name: Print result to log
        run: |
          echo "Attacker controlled workflow ran with input ${{ github.event.inputs.injection_point }}"


