name: Pull Request Triggered Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'workflow_trigger'

jobs:
  auto_update:
    runs-on: ubuntu-24.04

    steps:
      - name: Create GitHub App Token
        run: echo '🤖 Workflow triggered by attacker!'
