name: Pull Request Triggered Workflow

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'workflow_trigger'

jobs:
  run_script:
    runs-on: ubuntu-24.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ steps.app-token.outputs.token }}

    - name: Run benign script
      run: bash workflow_script.sh 
